---
# Ubuntu tasks file for ansible-role-pritunl-server

- name: Ensure apt key for pritunl server is present
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ pritunl_server_key }}"

- name: Ensure apt repository for pritunl server is present
  apt_repository:
    repo: "{{ pritunl_server_repo }}"
    filename: pritunl
    update_cache: yes
    state: present

- name: Ensure pritunl server is present
  apt:
    name: pritunl={{ pritunl_server_version }}
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Ensure apt key for mongodb server is present
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ mongodb_server_key }}"

- name: Ensure apt repository for mongodb server is present
  apt_repository:
    repo: "{{ mongodb_server_repo }}"
    filename: mongodb
    update_cache: yes
    state: present

- name: Ensure mongodb server is present
  apt:
    name: mongodb-org
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes
  
# Hotfix for pritunl installer (empty mongodb_uri in /etc/pritunl.conf after installation)
- name: Ensure mongodb server is present into /etc/pritunl.conf
  lineinfile:
    path: /etc/pritunl.conf
    regexp: '^.*"mongodb_uri": ""$'
    line: '    "mongodb_uri": "mongodb://127.0.0.1:27017/pritunl"'